services:

####
# Discord Bot
####
  bot:
    image: horeak/the-armory
    container_name: DiscordBot
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
        - lavalink
    volumes:
      - ${VPATH}/discordData:/app/discordData
    ports:
      - "8000:8000"
    networks:
      - lavalink
      - gelf
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "armory"
###
# LavaLink
###
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:3
    container_name: LavaLink
    environment:
      - LAVA_OPTS=-Xmx512m
      - SERVER_PORT=2333
      - LAVALINK_SERVER_PASSWORD=${LAVALINK_PASSWORD}
    restart: unless-stopped
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "lavalink"
    networks:
      - gelf
      - lavalink

####
# Seq
####
  seq:
    container_name: Seq-Logging
    image: datalust/seq:latest
    ports:
      - "5341:80"
    environment:
      ACCEPT_EULA: "Y"
      SEQ_ADDRESS: "http://seq:5341"
    restart: unless-stopped
    volumes:
      -  ${VPATH}/seq-data:/data
    networks:
      - seq

  seq-input-gelf:
    image: datalust/seq-input-gelf:latest
    depends_on:
      - seq
    ports:
      - "12201:12201/udp"
    environment:
      SEQ_ADDRESS: "http://seq:5341"
    restart: unless-stopped
    networks:
      - seq
      - gelf

networks:
  seq:
  gelf:
  lavalink: